server:
  port: 3003 
  error: 
    include-stacktrace: never

upload:
  dir:
    photos: "src/main/resources/photos/"

backend:
  api: "http://localhost:3003/"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/Almeidas_Cortes?createDatabaseIfNotExist=true
    username: root
    password: 1234

  servlet:
    multipart:
      enabled: true

  jpa:
    show-sql: true