server:
  port: 3003 
  error: 
    include-stacktrace: never

upload:
  dir:
    photos: "src/main/resources/photos/"

backend:
  api: "${API_BACKEND:http://192.168.0.13:3003/}"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE_HOST:localhost}:3306/${DATABASE_DATABASE:Almeidas_Cortes}?createDatabaseIfNotExist=true&serverTimezone=GMT-3
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:1234}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    show-sql: true
    ddl-auto: none