server:
  port: 3003 
  error: 
    include-stacktrace: never

upload:
  dir:
    photos: "src/main/resources/photos/"

backend:
  api: "${API_BACKEND:http://192.168.0.9:3003/}"

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DATABASE__HOST:localhost}:${3306}/${DATABASE_DATABASE:Almeidas_Cortes}?createDatabaseIfNotExist=true
    username: ${DATABASE_USERNAME:root}
    password: ${DATABASE_PASSWORD:1234}
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 10MB

  jpa:
    show-sql: true