CREATE TABLE tab_users (
    id INT AUTO_INCREMENT PRIMARY KEY,
    name VARCHAR(250) NOT NULL,
    user VARCHAR(250) NOT NULL,
    password VARCHAR(255) NOT NULL DEFAULT "$2a$10$BBwprwELNNYUfHpYQ.TcEu1o2rXPc3ZFY9LtVHGz8Zu..vNeuwu1G",
    first_Login DATETIME DEFAULT null,
    last_Login DATETIME DEFAULT null,
    active BOOLEAN NOT NULL DEFAULT 1
);
