name: CI

on:
  push:
    branches: [develop]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
      - uses: actions/checkout@v5

      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            caiqueerodrigues/almeidas:v1
            caiqueerodrigues/almeidas:latest
