# name: "Deploy VPS"
# on:
#   push:
#     branches: [develop]

# jobs:
#   CI:
#     runs-on: ubuntu-latest

#     steps:
#       - name: Baixar o código
#         uses: actions/checkout@v5

#       - name: Docker Login
#         uses: docker/login-action@v3.6.0
#         with:
#           username: ${{ secrets.USER }}
#           password: ${{ secrets.PASSWORD }}

#       - name: Build and push Docker images
#         uses: docker/build-push-action@v6.18.0
#         with:
#           context: .
#           file: Dockerfile
#           push: true
#           tags: |
#             caiqueerodrigues/almeidas:v1
#             caiqueerodrigues/almeidas:latest
#             caiqueerodrigues/almeidas:${{ github.sha }}

name: "Deploy VPS"
on:
  push:
    branches: [develop]

jobs:
  CI:
    runs-on: ubuntu-latest

    steps:
      - name: Baixar o código
        uses: actions/checkout@v5

      - name: Docker Login
        uses: docker/login-action@v3.6.0
        with:
          username: ${{ secrets.USER }}
          password: ${{ secrets.PASSWORD }}

      - name: Build and push Docker images
        uses: docker/build-push-action@v6.18.0
        with:
          context: .
          file: Dockerfile
          push: true
          tags: |
            caiqueerodrigues/almeidas:v1
            caiqueerodrigues/almeidas:latest
            caiqueerodrigues/almeidas:${{ github.event.head_commit.message | slugify }}

      - name: Instalar Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/$(curl -s https://api.github.com/repos/docker/compose/releases/latest | jq -r .tag_name)/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose

      - name: Rodar Docker Compose
        run: |
          docker-compose -f docker-compose.yml up -d

      - name: Limpar imagens antigas
        run: docker system prune -af


# name: "Deploy VPS"
# on:
#   push:
#     branches: 
#       - develop

# jobs:
#   build_deploy:
#     runs-on: ubuntu-latest

#     steps:
#       - name: "Baixar o código"
#         uses: actions/checkout@v5.0.0

#       - name: "Copiar docker-compose.yml para o servidor"
#         uses: appleboy/scp-action@master
#         with:
#           host: ${{ secrets.VPS_HOST }}
#           username: ${{ secrets.VPS_USER }}
#           password: ${{ secrets.VPS_SSH_PASSWORD }}
#           source: "docker-compose.yml"
#           target: "/almeidas"

#       - name: "Deploy via SSH"
#         uses: appleboy/ssh-action@master
#         timeout-minutes: 60
#         with:
#           host: ${{ secrets.VPS_HOST }}
#           username: ${{ secrets.VPS_USER }}
#           password: ${{ secrets.VPS_SSH_PASSWORD }}
#           script: |
#             cd /almeidas
#             docker-compose pull
#             docker-compose down
#             docker-compose up -d